### ISSUE TITLE
Custom sensors

### ISSUE THREAD

**Issue by KarimSouilmi** [jimmy-landry/HA-Mobile-Dashboard-Config#5]
Hi Jimmy,

Thnx a lot for posting this beautiful dashboard.

Correct me if I'm wrong but is a sensor like sensor.pending_update_counter and light.active_bedroom_lights a custom sensor?

If yes can you post the code of all custom sensors?

Thnx in advance.

Karim

**Comment by jimmy-landry** [comment]
Yes--those are all custom sensors. Check issue #1 for the pending updates counter, because there's a couple different ways you can do it. As for the active bedroom lights, I was able to get that working by following [this community thread](https://community.home-assistant.io/t/light-group-for-lights-that-are-already-on/296398/15). Add your entities in the regular group, use that group in the custom light template, and you should be good to go.

**Comment by KarimSouilmi** [comment]
Thnx for youre response.

I got the update entitie working by this code:

{{states.update | selectattr('state', 'eq', 'on') | list | count}}
